### PR TITLE
Fix swiftlint superflous disable errors

### PR DESCRIPTION
**Pull request by KITSSebSkuse**
Fixes compile errors using Swiftlint 0.23.1:

screen shot 2017-10-26 at 12 26 19

### CODE REVIEW

**Review by Neil3079 — APPROVED** [review]

**Comment by samdods** [comment]
why is this needed? the swiftlint version for linting this repo should be pinned, and any consumer's linting should exclude dependencies. i see no reason for this update, we wouldn't want to make a similar update every time a new version of swiftlint is released.

**Comment by KCWillRochaThomas** [comment]
@samdods is your concern that this disable is needed in earlier swiftlint versions? in which case, isn't it better to support the most recent over old & get people to upgrade?

**Comment by KITSDavidHardiman** [comment]
How have you pinned the swiftlint version? If we know how you're intending to do that we might be able to do similar, but at the moment, we're using the version mentioned above and that means we can't build TABResourceLoader using Carthage. So this is required for us or we can no longer use the upstream version of TABResourceLoader.

**Comment by samdods** [comment]
you shouldn't lint dependencies. they should be excluded in .swiftlint.yml

**Comment by samdods** [comment]
if you lint all of your dependencies then surely TABResourceLoader will be the least of your worries

**Comment by KITSDavidHardiman** [comment]
Turns out we do have Carthage/ excluded in our .swiftlint, so I've misunderstood the reason why we've contributed this fix. Apparently TRL tries to lint itself as one of its build steps, and that picks up the version we've got installed and causes the failure. I appreciate you tend to use cocoa pods, but I understood when we first agreed to use this that Carthage was supported. Regardless though, I'd like to understand the mechanism through which you're pinning the swiftlint version. We tend to keep up to date with swiftlint, so if we do need to make changes or contributions to TRL, we need to understand how you're specifying that version so we can play along. If the answer to that question is simply "we don't upgrade beyond the version we've currently got installed on our machines" then we'll just maintain our own fork of the project because we prefer to keep up with developments of the tools we use.

**Comment by KITSSebSkuse** [comment]
We don't lint our dependencies.

TABResourceLoader has a build phase that lints on build (which is _not_ pinned, it uses the version of swiftlint in the user's PATH):

screen shot 2017-11-08 at 13 27 44

Swiftlint picks up it's config from the path it's run from. Because it's run from inside `TABResourceLoader`, it uses the swiftlint rules specified there rather than the ones from our project, so is not excluded. 

If you use Carthage to build TABResourceLoader, it will fail with the above error unless you're running the very specific, old, version of Swiftlint on your machine.

**Comment by KITSDavidHardiman** [comment]
Perhaps this isn't the solution to the problem then, perhaps linting should be limited to debug builds only, as that might solve the issue without the controversy of which rules you wish to adopt and which you don't?

**Comment by samdods** [comment]
@KITSDavidHardiman I wouldn't want to limit to debug builds only, because we want it to be picked up by CI, to prevent any lint-failing code reaching `master`.

@KITSSebSkuse I see the problem, I didn't realise that this build phase was executed when using Carthage. That doesn't happen when dependencies are installed using CocoaPods.

I'll investigate a better solution for this. But ultimately we shouldn't have to update this codebase every time a new version of SwiftLint is released. It'll be a nightmare to maintain if we're depending on the consumer's local version of SwiftLint.

**Comment by samdods** [comment]
@KITSDavidHardiman a better solution would be if we could detect that the build is a Carthage-installed dependency and skip the linting.

**Comment by KITSDavidHardiman** [comment]
Doesn't `xcodebuild test` run a debug configuration?

**Comment by samdods** [comment]
Maybe @KITSDavidHardiman, but I have a feeling this Project setting may override the scheme setting:
screen shot 2017-11-08 at 18 32 13

But still, perhaps we can just change that setting and only run linting for Debug builds, as suggested.

**Comment by samdods** [comment]
Maybe @KITSDavidHardiman, but I have a feeling this Project setting may override the scheme setting:
screen shot 2017-11-08 at 18 32 13

But still, perhaps we can just change that setting and only run linting for Debug builds, as suggested.

**Comment by samdods** [comment]
Maybe @KITSDavidHardiman, but I have a feeling this Project setting may override the scheme setting:
screen shot 2017-11-08 at 18 32 13

But still, perhaps we can just change that setting and only run linting for Debug builds, as suggested.

**Comment by samdods** [comment]
Maybe @KITSDavidHardiman, but I have a feeling this Project setting may override the scheme setting:
screen shot 2017-11-08 at 18 32 13

But still, perhaps we can just change that setting and only run linting for Debug builds, as suggested.

**Comment by KITSDavidHardiman** [comment]
I think
screen shot 2017-11-08 at 18 36 25
in the scheme supersedes that setting in the project.

**Comment by KITSDavidHardiman** [comment]
You shouldn't change that setting though, otherwise you'll end up with Carthage users with debug builds, which (you|I) definitely don't want...

**Comment by KITSDavidHardiman** [comment]
Sorry, I mean:
screen shot 2017-11-08 at 18 41 17

**Comment by KITSDavidHardiman** [comment]
Bearing in mind you've got a shared scheme already or Carthage wouldn't work at all.

**Comment by samdods** [comment]
@KITSDavidHardiman, are there any environment variables to indicate that this is building as a Carthage dependency? seems like we need a way to detect that. making a decision on the Configuration isn't the right way, because consumers will need to build their project with both Debug and Release.

**Comment by KITSDavidHardiman** [comment]
Not sure, never spent much time in the Carthage code, or ever encountered an issue like this before. Possible other issue, could you change lint severity for settings to warning rather than error and somehow fail the build for warnings on CI? That way Carthage users never see them, but you still get the security you're after.

**Comment by samdods** [comment]
Carthage users would still see those warnings though. They'd add noise to your build. I'll investigate here and try to think up a solution that works for Carthage.

**Comment by samdods** [comment]
@KITSDavidHardiman can you send me the env vars output please? tap the icon on the right to expand the big green panel of variables and send the whole lot please :)

screen shot 2017-11-09 at 14 18 21

**Review by samdods — CHANGES_REQUESTED** [review]
requesting changes to prevent this from being merged without further consideration

**Comment by KITSDavidHardiman** [comment]
What env vars do you want? I'd run Carthage from the command line not from Xcode so there's no button to tap?

**Comment by samdods** [comment]
i mean for the swiftlint build phase

**Comment by KITSSebSkuse** [comment]
I'm not sure an environment variable dump from Xcode is going to help. Carthage builds via the commandline and uses xcodebuild - not Xcode. Carthage have also [specifically stated](https://github.com/Carthage/Carthage/issues/1148) no environment variables are set during a build.

Maybe we should fix the actual underlying issue here, which is to not use single-underscore prefixed variable names? The reason there's a swiftlint rule for this is Apple specifically state you [should not do it](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html) as it's reserved for their use.

**Comment by samdods** [comment]
@KITSSebSkuse Carthage might install via the command line, and you might use xcodebuild for your CI builds, but once the dependencies are installed and you're running your builds from Xcode GUI, then surely it is the open GUI instance of Xcode that is building the dependencies.

but i'm happy to get this merged anyway. we'll just have to figure out a way to prevent swiftlint from running when installed as a Carthage dependency.

**Comment by samdods** [comment]
thanks for brining this issue to our attention 👍

**Review by samdods — APPROVED** [review]

**Comment by KITSDavidHardiman** [comment]
@samdods Carthage builds dynamic frameworks, which we just link in our project. It's not involved in the Xcode GUI at all... So the error's only ever an issue from the command line.

**Comment by KITSDavidHardiman** [comment]
Thanks for merging though :)

**Pull request merged**
